import random



lista =  [1,2,3,4,5,6,7,8,9,10]
n_aleatorio  = random.randint(1,10)
lista.remove(n_aleatorio)
print(lista)



# # estrura de dado


# variavel = 10


# # cabe apenas 1 dado



# lista  =  []
# #                      -  -2  -1
# lista_2 = [1,2,3,4,5,6,7,8,9]
# #         0  1  2 3 4 5 6 7 8



# print(lista_2[8])
# lista_3 = list(range(1,2000)) 



# # funções para adicionar 



# lista_2.append(110) # add apenas 1  dado (append)
# print(lista_2)


# lista_2.insert(7, 300)
# print(lista_2)
# # função remover


# lista_2.extend([10,20,30,10,20,30])
# print(lista_2)



# lista_2 += (20,30360500,403070)
# print(lista_2)


# # remover dados 



# lista_2.remove(30360500) # remove o que você vê
# print(lista_2)


# lista_2.pop()
# print(lista_2) # remove o último valor


# lista_2.pop(0) # remove a partir do indice
# print(lista_2)


# del lista_2[6]
# print(lista_2)



# # slice -  fatiamento
# nova_lista = lista_2[5:9]


# print(nova_lista)




